### ISSUE TITLE
Failing dex2jar on API 24+ apps

### ISSUE THREAD

**Issue by aph3rson** [MobSF/Mobile-Security-Framework-MobSF#1037]
## ENVIRONMENT

OS and Version: W10x64 (1803)
Python Version: PYthon 3.7.2
MobSF Version: Pulled off master (3bc43195d87401aca51b0eb298ced98f1582ccf2)

## EXPLANATION OF THE ISSUE

Running static analysis on an Android app built for Android 7+ (new DEX format) fails the dex2jar step. This appears to be due to pxb1988/dex2jar#93. An [unofficial fork](https://github.com/DexPatcher/dex2jar) exists courtesy of @Lanchon, which adds support for Android 7/8 dex files.

## STEPS TO REPRODUCE THE ISSUE

1. Download a jar compiled for Android N or greater (API 24).
2. Run through the static analyzer.
3. Observe that dex2jar fails on the Java output stage, but smali code works as expected.

## LOG FILE

Relevant portions of console output from code analysis:
```
[INFO] 05/Aug/2019 17:23:20 - DEX -> JAR
[INFO] 05/Aug/2019 17:23:20 - Using JAR converter - dex2jar
[INFO] 05/Aug/2019 17:23:20 - Converting classes.dex to JAR
[INFO] 05/Aug/2019 17:23:20 - Running JAVA path fix in Windows
dex2jar C:\Tools\Mobile-Security-Framework-MobSF\uploads/fd1881009bce67541dffb8f60647dcbf\classes.dex -> C:\Tools\Mobile-Security-Framework-MobSF\uploads\fd1881009bce67541dffb8f60647dcbf\classes0.jar
com.googlecode.d2j.DexException: not support version.
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:151)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:211)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
[INFO] 05/Aug/2019 17:23:20 - Converting classes2.dex to JAR
[INFO] 05/Aug/2019 17:23:20 - Running JAVA path fix in Windows
dex2jar C:\Tools\Mobile-Security-Framework-MobSF\uploads/fd1881009bce67541dffb8f60647dcbf\classes2.dex -> C:\Tools\Mobile-Security-Framework-MobSF\uploads\fd1881009bce67541dffb8f60647dcbf\classes1.jar
com.googlecode.d2j.DexException: not support version.
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:151)
        at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:211)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
[INFO] 05/Aug/2019 17:23:20 - DEX -> SMALI
[INFO] 05/Aug/2019 17:23:20 - Converting classes.dex to Smali Code
[INFO] 05/Aug/2019 17:23:28 - Converting classes2.dex to Smali Code
```

**Comment by ajinabraham** [comment]
At the moment we can't refer to unofficial builds. 
Alternatively you can use enjarify instead of dex2jar

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L266

**Comment by aph3rson** [comment]
Thanks for the information - perhaps, instead of closing this issue without action, we could update the documentation to mention that there's an option available here?

**Comment by Lanchon** [comment]
dex2jar is mostly abandonware since 2015; check out the commit history.

enjarify is abandonware too. the author never maintained it and refused my requests for enhancements. the developer time on enjarify was paid by google; google does not want to continue to fund it, and its author does not want to donate any of his time to the project. so enjarify is a dead project until such time somebody forks it. it does not support the newer dex formats, and it does not translate dalvik/jvm specific annotations (eg: annotations fully describing generic types after type erasure).

i dont know what is "official" about the particular original author of an open source project. maybe you should use brutall's version of Apktool, which he abandoned in 2011.

i will not maintain dex2jar; but for now my fork works. on the longer term, if dex to jar translation is required for your proyect, you will have to provide your own solution or let your project die.

the most future-proof d2j would be jvm code based on D8/R8 code sponsored by google and ASM, which is used by projects that cannot die. i think that ASMDEX is abandonware, unfortunately. some of my projects are based on smali's dexlib2. while technically sound (muuuuch more than dex2jar's code which is a quick-hack mess), i have doubts of it being maintained in the future. D8/R8 should be capable of reading an writing dex, and is the canonical dex writer of the android platform. dexlib2 is used by google to validate its canonical tools via an independent implementation, but its future is unclear to me.

**Comment by Lanchon** [comment]
btw, my fork is sort of documented here:
https://github.com/DexPatcher/dex2jar/releases

**Comment by ajinabraham** [comment]
@Lanchon Do you plan to maintain this? @superpoussin22 @matandobr @magaofei What do you think?

**Comment by Lanchon** [comment]
hi,

i don't commit to supporting dex2jar. the codebase is kind of a mess. i only fixed it so far because my dexpatcher project needs it for some optional functionality and it was low hanging fruit.

enjarify exists in 2 versions: rust and (i think) python. (one of them is unmaintained i think.) it is more of a one time exercise, than a maintained product.

unfixable deficiencies are:
- developed in languages that do not target the jvm:
  - cannot consume mature bytecode libs.
  - cannot be hosted in the jvm/dalvik ecosystems.
- recreates the wheel:
  - reads dex bytecode directly instead of using D8/R8's dex i/O or smali's dexlib2.
  - writes jvm bytecode directly instead of using ASM lib.

this is why i see the need for a new project, which would best be kotlin or java consuming mature jvm libs (might include D8 or a fork of it). i do not have the bandwidth for it.

**Comment by ajinabraham** [comment]
For our project, we don't really need jar files. All we care us Java and Smali source. We are planning to replace our jar based decompilers and dex2jar with jadx.

**Comment by superpoussin22** [comment]
take a look at PR #1030

**Comment by ajinabraham** [comment]
Replaced with jadx
