### ISSUE TITLE
SEVERITY 	CVSS Rating 

### ISSUE THREAD

**Issue by Kevintroll** [MobSF/Mobile-Security-Framework-MobSF#1176]
How your application giving ratings. 7.4 High, 0 also High, 7.5 is info. Please Explain the Procedure for making a report

Example

  ﻿
![image](https://user-images.githubusercontent.com/53478733/69407649-43dd8080-0cc2-11ea-8d6c-55f5f8a25559.png)

**Comment by ajinabraham** [comment]
The severity and CVSS score are not related.

Requesting Super user does not comes under CVSS and hence the score is zero.
The severity is given high because it can be a possible malware behaviour. All apps available on playstore are designed to work without super user privileges. A lot of malicious apps request for root.

Again please use slack channel for discussions! Github issues are strictly for reporting bugs.
