### ISSUE TITLE
Dynamic Analysis bug make changes in http_proxy

### ISSUE THREAD

**Issue by nitin3thakur** [MobSF/Mobile-Security-Framework-MobSF#1416]
After running dynamic analysis using MobSF, Genymotion show connection error.
"ERR_PROXY_CONNECTION_FAILED"

wifi proxy reset, reboot VM and MobSF don't work.

I found a solution on internet. Running following command, restore/unset http_proxy and everything is smooth again.
adb shell settings put global http_proxy :0

Bug in report generation does not reset http_proxy. Hence facing this issue.

Reference: 
https://android.stackexchange.com/questions/219591/fix-err-proxy-connection-failed-due-to-a-change-in-global-proxy-by-mobile-securi/219593#219593?newreg=c561923bd78f475eaa2afd285d950447

**Comment by ajinabraham** [comment]
If you Generate Report after dynamic analysis, MobSF should unset the global http proxy.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android/environment.py#L193

Have you generated a report from MobSF after Dynamic Analysis and still see this issue?

**Comment by germinalx** [comment]
Same here.. I thought it was a genymotion or virtualbox problem, I re-installed everything but I realized that it is only when I ran the dynamic analysis, I tried with other APIs, MobSF in linux and Windows, change NAT and Bridge address in Geny and the problem is the same, even if I close MOBsf the emulator keeps the network error (with valid ip)

How do I execute the report indicated above?

**Comment by nitin3thakur** [comment]
Yes. I generated report after dynamic analysis. However, this issue was not resolved. It requires manually resetting of http_proxy.

**Comment by ajinabraham** [comment]
Fixed on 3.1.1

**Comment by Gunkkk** [comment]
> Fixed on 3.1.1

still there in 3.1.1

**Comment by RussellMurad** [comment]
I facing the same issue in v3.4.3...
