### ISSUE TITLE
Malware isolation and snapshots

### ISSUE THREAD

**Issue by vandir** [MobSF/Mobile-Security-Framework-MobSF#1607]
I'm just trying the framework with some sample in order to understand if it can fit my needs. I think it's a great framework but I did not understand two things about dynamic analysis by using Android emulator (I can't use Genymotion):

- How can I isolate the virtual environment? I would like to disable the Internet connection of the emulator to avoid real contacts to the malicious domains. 

- Does MobSF rely automatically on snapshots? How can I assume that the dynamic analysis always start with a "clean" emulator? Should I manually wipe the emulator or switch to a clean snapshot each time?

Thanks

**Comment by ajinabraham** [comment]
For discussions and questions please use MobSF Slack Channel. Github issues are only for bug tracking.
1. You could setup an upstream proxy on MobSF and intercept or drop the outgoing traffic. Or set an invalid upstream proxy in settings so that networking connections won't work.
2. The docs state to start without snapshot. You could also modify the startup command for AVD to wipe data/reset etc. as per your requirements.
