### ISSUE TITLE
Cod Analyssis and Shared Library Binary Analysis are wrong

### ISSUE THREAD

**Issue by anda5** [MobSF/Mobile-Security-Framework-MobSF#1676]
Based on this comments: https://github.com/xamarin/xamarin-android/issues/5592 It looks like MOBSf has some scanning issues at  CODE ANALYSIS and  SHARED LIBRARY BINARY ANALYSIS 
![106896728-a3268580-66fa-11eb-8d72-4cfd6a67d077](https://user-images.githubusercontent.com/9405801/108046836-c3850700-704d-11eb-826b-3e4ab5aa7990.png)

**Comment by anda5** [comment]
[app_scan.pdf](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/5995403/app_scan.pdf)

**Comment by ajinabraham** [comment]
You should ignore any code analysis findings that's not applicable to you or is a false positive.

Regarding binary analysis, MobSF uses LIEF project for Binary Analysis.

The findings under PIE is wrong as the checks are for PIE instead of PIC for shared objects. Opened up a question upstream. https://github.com/lief-project/LIEF/issues/555

Rest of the results are directly from LIEF project. If you see anything reported incorrectly. You should reach out to them.

**Comment by ajinabraham** [comment]
Fixed the PIE issue  in latest master

**Comment by anda5** [comment]
@ajinabraham thank you so much for fix and investigate this.

**Comment by anda5** [comment]
https://github.com/lief-project/LIEF/issues/557#issuecomment-806523396

**Comment by ajinabraham** [comment]
The FORTIFY_SOURCE detection is done by looking for `_chk` in symbols. Those `.so` files didn't had a `_chk` symbol.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/d7823dc878764d6124501d2e722eeb1f472b47df/mobsf/StaticAnalyzer/views/android/binary_analysis.py#L223

You could cross check the findings using a tool like https://github.com/slimm609/checksec.sh after extracting the `.so` files from your APK and running checksec on them.

**Comment by AjitKRuin** [comment]
Hi @ajinabraham ,
Here in my mobile app , I am facing the stack canary as false issue while pen test with **Mobsf** tool in file naming **libxamarin.so**
