### ISSUE TITLE
False negative : SSL Pinning Detection

### ISSUE THREAD

**Issue by debasishm89** [MobSF/Mobile-Security-Framework-MobSF#1763]
## ENVIRONMENT

```
OS and Version: Any
Python Version: 3.8
MobSF Version: 3.4.4. Latest
```

## EXPLANATION OF THE ISSUE

MobSF checks presence of ssl pinning by looking at a pattern : "setHostnameVerifier"

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/083d27272a3f8de0a31489d99659c289af856ba1/mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml#L286

So when SSL pinning forcefully disabled in follwing way MobSF show its as secure, however that is not the case.

https://github.com/HTBridge/pivaa/blob/7fde8956083ec4c6023c75f013f72023d60eda12/app/src/main/java/com/htbridge/pivaa/handlers/API.java#L80

```
        try {
            URL url = new URL(inputedURL);

            if (url.getProtocol().toLowerCase().equals("https")) {
                trustAllHosts();
                HttpsURLConnection https = (HttpsURLConnection) url.openConnection();
                https.setHostnameVerifier(DO_NOT_VERIFY);
                urlConnection = https;
            } else {
                urlConnection = (HttpURLConnection) url.openConnection();
            }
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Scan https://github.com/HTBridge/pivaa APK with MobSF
2. You should see an issue as "This App uses SSL certificate pinning to detect or prevent MITM attacks in secure communication channel." -

```

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```

**Comment by ajinabraham** [comment]
Hi @debasishm89 Thanks for reporting this.

The method `setHostnameVerifier` is used for both implementing pinning and bypassing SSL certificate errors.
The code analysis should have shown both of them in the results instead of one.

We are in the process of switching MobSF core to semgrep powered mobsfscan and this rule already covers the example you shared: https://github.com/MobSF/mobsfscan/blob/main/mobsfscan/rules/semgrep/network/accept_self_signed.yaml#L17

**Comment by debasishm89** [comment]
I could see only one entry in the the pdf report. Anyway it makes sense! 
Thanks Ajin!
Cheers,
