### ISSUE TITLE
CSS file loading fail in China

### ISSUE THREAD

**Issue by magaofei** [MobSF/Mobile-Security-Framework-MobSF#1870]
the page loading time is more than 15 seconds.
Because live-in China users do not access `fonts.googleapi.com` site.
Could we put the font file in the code repository or use CDN?

![image](https://user-images.githubusercontent.com/3363787/145707285-7c3b678f-92b1-429e-aad9-c43e2410723d.png)

```html
      <!-- Google Font: Source Sans Pro -->
      <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
```

**Comment by glitchdawg** [comment]
If we can retrieve the user's location, we can replace Google Fonts with  a CDN service that mirrors Fonts and Libraries from Google API, to serve visitors from China. UnfortunatelyI could not find any such service, One service that did work called useso libraries has stopped providing this service since August 31, 2016. If we find an equivalent service then we can mitigate this issue

**Comment by ajinabraham** [comment]
This can be fixed by self hosting fonts.

For example for https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700 needs around 10+ font files to be saved locally.

Unfortunately, we use a [couple](https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=fonts.googleapis&type=code) of google fonts and the no of files requires increases. It's a tedious work, but I am not prioritizing this. If anyone is interested, they can help in collecting all font files and doing a PR.

**Comment by ajinabraham** [comment]
Tracked separately
