### ISSUE TITLE
mobsf issue with python3.11 

### ISSUE THREAD

**Issue by ahmedsamir286** [MobSF/Mobile-Security-Framework-MobSF#2151]
Dear All, 

I found an issue installing the MobSF using python3.11, 
the error is : 
[ERROR] MobSF dependencies require Python 3.8 - 3.10. You have Python version 3.11.2 or python3 points to Python 3.11.2.

Thanks.

**Comment by akirataguchi115** [comment]
The setup.sh seems to work only with 3.8-3.9. Dunno why the setup.py defines the working range to be 3.8-3.10.

Create an alias for your python to be python3.9 and it should work.

**Comment by ahmedsamir286** [comment]
@akirataguchi115 
so should I write ?
alias python3.9=python3 
in my .bashrc file .

**Comment by akirataguchi115** [comment]
Actually maybe no. I noticed that I myself couldn't make the script work with the aliases. Maybe some linux-head could help us on how to manage python versions inside shell scripts.

**Comment by ITmustang** [comment]
@akirataguchi115 use pyenv, itll let you use a specific python version inside a specific directory.

**Comment by akirataguchi115** [comment]
`pyenv global 3.9` worked for me and setup.sh was succesful. What about you, OP? Also do we have an issue open for Python 3.10+ somewhere?

**Comment by jcsimancas** [comment]
> Dear All,
> 
> I found an issue installing the MobSF using python3.11, the error is : [ERROR] MobSF dependencies require Python 3.8 - 3.10. You have Python version 3.11.2 or python3 points to Python 3.11.2.
> 
> Thanks.

Hi, Were you able to resolve this issue?, I've the same problem-

**Comment by akirataguchi115** [comment]
@jcsimancas Do you have Python11 installed as well? Did you try pyenv?

**Comment by ajinabraham** [comment]
Please use slack channel for support.

**Comment by ajinabraham** [comment]
This is not a MobSF issue, some of the dependencies doesn't compile, build or have prebuilt wheels/egg available on newer python versions. We are spammed by support request on fixing these issues which are not in our control. You could use something like pyenv to install a specific version of python for a particular project.

**Comment by mxteenkhxn** [comment]
`[https://github.com/pyenv/pyenv](url)`
Use this above repository and the mentioned instructions to downgrade to python 3.10-3.11 or any version you would like to downgrade to.

**Comment by White000Devil** [comment]
pip install color
Defaulting to user installation because normal site-packages is not writeable
Collecting color
  Using cached color-0.1.1.tar.gz (3.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/88/04/0defd6f424e5bafb5abc75510cbe119a85d80b5505f1de5cd9a16d89ba8c/color-0.1.1.tar.gz (from https://pypi.org/simple/color/): Requested color from https://files.pythonhosted.org/packages/88/04/0defd6f424e5bafb5abc75510cbe119a85d80b5505f1de5cd9a16d89ba8c/color-0.1.1.tar.gz has inconsistent version: expected '0.1.1', but metadata has '0.1'
ERROR: Could not find a version that satisfies the requirement color (from versions: 0.1.1)
ERROR: No matching distribution found for color
