### ISSUE TITLE
Include new Semgrep rules from semgrep-rules-android-security

### ISSUE THREAD

**Issue by gand3lf** [MobSF/Mobile-Security-Framework-MobSF#2195]
Hi, recently I work on a collection of Semgrep rules to cover the static tests described by the OWASP MASTG.
This is the official repo: https://github.com/mindedsecurity/semgrep-rules-android-security

Why not include these rules in MobFS? :smiley:
Hope you like it! :+1:

**Comment by ajinabraham** [comment]
These rules look well put out. Thanks for sharing it.

MobSF is yet to move to Semgrep for SAST due to it’s lack of cross platform support and potential slowdown when dealing with large decompiled APKs. 

This seems like a right fit for [mobsfscan](https://github.com/MobSF/mobsfscan) our CLI that uses semgrep [rules](https://github.com/MobSF/mobsfscan/tree/main/mobsfscan/rules/semgrep) which acts on source code directly.

**Comment by ajinabraham** [comment]
I am going to move this to mobsfscan repo and close it here.
