### ISSUE TITLE
INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by reignseth87** [MobSF/Mobile-Security-Framework-MobSF#2294]
Hi guys! I am trying to install MobSF on my kali (VirtualBox).... I followed all the procedures... But after running it... (./run.sh and clicking on the ip)... I get an error... "Internal Server Error"... How do I fix this please.... I need this urgently

**Comment by reignseth87** [comment]
Thank you.

**Comment by baptx** [comment]
This issue was kind of a bug that is useful to have on GitHub for reference.
I got this issue too when switching from version 3.6.0 to 3.7.6 and here is what I did in case it helps someone (maybe not all steps are necessary):
I removed the .MobSF folder and the content in .local/bin/ folder (be careful that it does not contain files you want to keep).
Execute setup.sh and then run.sh.
I don't know why some dependencies were installed in .local/bin/ folder because MobSF worked fine with the dependencies in .local/lib/python3.9/site-packages/ fodler on Debian.

**Comment by 0xruw** [comment]
> i'm facing this issue while login to mobsf with default cridientials
> 
> ```
> Server Error (500)
> 
> This request caused an Internal Server error. Check the server logs for more details. For debugging, try setting DEBUG=True in settings.py 
> ```

see this https://youtu.be/4nzt1uwuwf8?si=v1DDXEJlhJgUcO5Q

**Comment by baptx** [comment]
I had the error again like other people at https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/2409.
Installing the latest openjdk, removing the folders pip and pypoetry from the `.cache` folder and restarting `setup.sh` worked before `run.sh` worked.
This issue gave me a hint it was a cache issue since I had the same error:
https://stackoverflow.com/questions/54722170/django-sessionstore-object-has-no-attribute-session-cache
