### ISSUE TITLE
Too much data is loaded at one time, causing the browser to stall

### ISSUE THREAD

**Issue by xiaoliusec** [MobSF/Mobile-Security-Framework-MobSF#2305]
When the analyzed file is relatively large, a lot of data is generated. When the browser is used to access and view, the one-time loading of data is too much, which often leads to the browser not responding. Can this problem be optimized?

**Comment by ohyeah521** [comment]
This is because a large amount of data is loaded at one time, especially when some APKs have a lot of strings. Some large applications will have more than 6M of string information, which will cause the browser to load too much data at once and freeze. , I have also discovered this problem before, and it seems that it will not be improved in the short term.

**Comment by ajinabraham** [comment]
At some point we want to move out from the current way of rendering the whole data to HTML to use something like ReactJS and the MobSF REST APIs. But that would take time. I will track this separately.

**Comment by ajinabraham** [comment]
We did some QA to improve data load times for report pages. Have a look.

**Comment by ajinabraham** [comment]
Addressed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2351
