### ISSUE TITLE
[FEATURE]Can support ignoring some detected problems

### ISSUE THREAD

**Issue by junwei-liu** [MobSF/Mobile-Security-Framework-MobSF#2377]
I hope mobsf can support ignoring some detected problems and prevent these ignored problems from appearing in the report.

**Comment by junwei-liu** [comment]
Sorry, because I am in mainland China. So I can't join https://mobsf.slack.com/unsupported-geo#/.

**Comment by ajinabraham** [comment]
We do have suppression feature for a lot of findings. What are you trying to suppress in particular?

**Comment by jvictors-tp** [comment]
@ajinabraham I am also trying to find documentation on suppressing findings within the static analysis of an APK or IPA app file. For example, known behaviors or permissions that I'd like to ignore so that it isn't part of the scorecard. I see that there's a section to list suppressed findings, but there's no control to add new ones. I've gone through the documentation and the DEFCON video and I haven't seen how to do this. Can this be better documented?

**Comment by ajinabraham** [comment]
@junwei-liu @jvictors-tp Suppression is currently available for ` MANIFEST ANALYSIS, CODE ANALYSIS` for Android and ` IPA BINARY CODE ANALYSIS, CODE_ANALYIS` findings for iOS. There are columns at the end of the table that allow you to do so.
<img width="1176" alt="Screenshot 2024-05-20 at 9 41 52 AM" src="https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/4301109/a3697455-61cf-4ac8-ba78-91358a33bec2">

Some features like permissions does not contribute to a score and cannot be suppressed.
