### ISSUE TITLE
requirements.txt list specific library versions

### ISSUE THREAD

**Issue by tautology0** [MobSF/Mobile-Security-Framework-MobSF#346]
The requirements.txt file lists specific versions of some of the required libraries:
```
Django==1.10.b1
tornado==4.1
xhtml2pdf==0.0.6
html5lib==1.0b8
psutil==4.2.0
```
This is a very dangerous practice and can easily lead to getting things out of step or an apt-get/yum upgrade messing things up. These should be more generic, if possible.

Ideally it would be best if the required libraries are the same version as those packaged by common operating systems (so you don't end up having to use multiple package managers).

**Comment by ajinabraham** [comment]
You should use `virtualenv`

We are sticking to the versions as we know that these works in the OS we supports (Ubuntu, OSX, Windows 7,8,10). Above libs are not shipped by the OS. Also we bump up the versions once in a while.

Another reason is that some features won't work if the library version is changed.

**Comment by tautology0** [comment]
I disagree - I initially put up with this on Kali; but I've just tried to put it on vanilla Ubuntu and spent ages faffing around with pip to get this to install. A good design aim would be to be compatible with major libraries that are OS capable. i.e. I shouldn't have to use pip: apt-get should provide me with the libraries needed.

This behaviour just results in multiple different versions of the same libraries on the host and is dangerous (let alone a poor development practice). In a worse case scenario (although not in this case) it means you may have to use a version of a library with a security issue.

**Comment by tautology0** [comment]
Case in point: there is a security fix in Tornado 4.2.1 which could result in directory traversal:

**Comment by ajinabraham** [comment]
Thats why I recommended virtualenv for handling python packages. These third-party libs are required and like I mentioned some libs like xhtml2pdf==0.0.6, html5lib==1.0b8 etc needs to be on specific versions, otherwise they can cause issues. Another problem maker is Django==1.10.b1, people already having older versions of Django will have trouble and irresponsibly open them as issue. So considering all these we thought to go with specific versions so that most likely they won't fail at both sides.

As for Tornado we can update that. We normally update dependencies once in a while when such security issues arise.

**Comment by tautology0** [comment]
Fair enough
