### ISSUE TITLE
Multiple Errors on IPA File

### ISSUE THREAD

**Issue by DiskorD42** [MobSF/Mobile-Security-Framework-MobSF#360]
## EXPLANATION OF THE ISSUE

I'm running MOBSF under Mac and when I try to analyse an IPA File I get the follwing Errors:

[ERROR] - Cannot perform class dump (/Users/john/Documents/Mobile-Security-Framework-MobSF-0.9.4.1/StaticAnalyzer/views/ios/binary_analysis.py LINE 207 "class_dump = subprocess.check_output([class_dump_z_bin, bin_path]"): Command '['/Users/john/Documents/Mobile-Security-Framework-MobSF-0.9.4.1/StaticAnalyzer/tools/mac/class-dump-z', u'/Users/john/Documents/Mobile-Security-Framework-MobSF-0.9.4.1/uploads/f87bb5d3883ce3ea49f2a835ea45f859/Payload/hidden.app/hidden']' returned none-zero exit status -11

[ERROR] iOS Binary Analysis (/Users/john/Documents/Mobile-Security-Framework-MobSF-0.9.4.1/StaticAnalyzer/views/ios/binary_analysis.py, LINE 262 "binary_analysis_dict["bin_res"]  = otool_dict["anal] + cls_dump"): cannot concatenate 'str' and 'NoneType' objects

followed by two errors when saving to the db because NoneType objects don't have an attribute called '__getitem__'

**Comment by ajinabraham** [comment]
@DiskorD42 Can you share your IPA? I guess it's because (`status -11`) the class-dump-z shipped with MobSF is not compatible with your OS Arch. Can you try installing class-dump-z separately and give path to it here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L264 and try again.

**Comment by DiskorD42** [comment]
Unfortunatly i can't share the IPA with you. I'll try to follow your suggestion on re-installing class-dump-z. I'll let you know how this works you.

Thanks

**Comment by maxchill** [comment]
I'm having the same issue, also running on MacOSX.  I attempted to follow the advice, and downloaded class-dump-z on my own, and updated settings.py to reference my own executable.

Google code class-dump-z
md5 class-dump-z                                                                                                                                    
MD5 (class-dump-z) = 6f46d7f3056c4c4ceb0e28987dbb782d
https://code.google.com/archive/p/networkpx/downloads
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/networkpx/class-dump-z

MobSF Bundled class-dump-z
md5 tools/mac/class-dump-z                                                                                                         
MD5 (MobSF/StaticAnalyzer/tools/mac/class-dump-z) = 583bc57668d21788ff27b9b45c278738 

It resulted in the same -11 exit code.  Is there a newer download location for a class-dump-z than the dead google code repository?

Thanks.  Let me know if I can help in anyway.

**Comment by ajinabraham** [comment]
@maxchill @DiskorD42 
Can you try running `./class-dump-z` and see if you are able to successfully run it on your mac. (Give correct permissions). If everything works it should work with MobSF as well.

**Comment by DiskorD42** [comment]
I can run ./class-dump-z just fine. 
If i run it on my App file manually, it tells me: 
`Segmentation fault: 11`

I also noticed that i can't access the unzipped ipa file with the finder. It says that it can't open that program because it's not supported by my type of mac. 
With the terminal however everything works fine.

**Comment by ajinabraham** [comment]
It's not a MobSF issue, looks like an issue in 3rd party component or the IPA

**Comment by phillycheeze** [comment]
Also adding in that the I am getting the same error. Might be class-dump-z no longer supporting newer IPAs.

**Comment by ajinabraham** [comment]
That needs to be checked.

**Comment by affimnem** [comment]
I get the same for some apps I'm looking at. I guess the class-dump-z has trouble with Swift code, but I haven't dug into that. One thing is that the class-dump-z fails, but that leads to other errors and finally the DB saving fails, ending up with a dashboard report with no information. I.e. no "File Information", no "App Information", only "App Transport Security" shows up.
For a public app that shows the problems, try:
https://itunes.apple.com/se/app/collector-for-arcgis/id589674237

I have a workaround for the dashboard issue: adding a simple None check to the class-dump-z result, and set the value to an empty string. That removes all but the first error, and the info from the other tools ends up on the dashboard report. The two added lines is included as a diff. Since I'm no Python hacker, it can probably be shortened.
[binary_analysis.py-diff.txt](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/952743/binary_analysis.py-diff.txt)
(I did a git update today, so it should work against v0.9.5.2 Beta.)

FYI: the last two errors not shown in OP's message are:
```
[2017-04-24 17:59:21]
[ERROR] Updating DB (/Users/mbp1/Desktop/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py, LINE 95 "BIN_ANAL=bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'

[2017-04-24 17:59:21]
[ERROR] Rendering to Template (/Users/mbp1/Desktop/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py, LINE 33 "'bin_anal': bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'
```
I haven't look at db_interaction.py since the above fix/workaround does what I need now.

**Comment by ajinabraham** [comment]
I have added a better exception handling here

**Comment by affimnem** [comment]
Good thing!  I guess there should be similar and generic exception handling for the other tools as well, to make sure tool changes doesn't stop the other tools' output from showing up.
