### ISSUE TITLE
How to fix the Insecure Binary Analysis in iOS app

### ISSUE THREAD

**Issue by chaohaiding** [MobSF/Mobile-Security-Framework-MobSF#372]
## EXPLANATION OF THE ISSUE

I am running a binary analysis on the iOS app (hybrid, ionic app), there are two insecure items found:
```
Binary make use of banned API(s)	Insecure	The binary may contain the following banned API(s) 
alloca, strlen, sprintf, memcpy.

Binary make use of malloc Function	Insecure	The binary may use malloc function instead of calloc.
```

I am not sure this is related to the framework or not, just needs any advance. Thx a lot.

**Comment by ajinabraham** [comment]
It can happen that the libraries you use with your app might be using those APIs

**Comment by ajinabraham** [comment]
To get a better idea, scan with zipped source code

**Comment by irshadpc** [comment]
@ajinabraham How can we fix those issue, if the library originally served from Apple.

**Comment by ajinabraham** [comment]
@irshadpc Can you explain a bit more?

**Comment by ITmustang** [comment]
@ajinabraham ive run into this issue recently as well. many times, i have the ipa and/or apk files but no zipped source code and any code review is out of scope. having only the apk and ipa files, can mobsf better point out whether these findings are used by underlying ios libraries or underlying platforms such as xamarin,

**Comment by ajinabraham** [comment]
Share the apk where you see the issue. 
you can email ajin25 AT gmail DOT com

**Comment by ITmustang** [comment]
@ajinabraham, sent... email subj: ITmustang insecure API question

**Comment by ajinabraham** [comment]
@ITmustang Fixed a minor bug, everything works in the latest python3 branch. You can wait till that gets merged to master or use that branch for now. Note we are moving from python2 to python3.

**Comment by ajinabraham** [comment]
Also tested with your IPA and it works fine. Please note that for IPA, it can't do source code analysis as we cannot get the source code from the  binary object. If you need source code analysis, zip the source code and feed it to MobSF. Even with IPA you get info on few libraries and methods used. For APK it can decompile the code and gives you a source code analysis as well.

**Comment by poldenais** [comment]
Hi Ajin,
I get similar issues when testing an IPA in MobSF:

_

> The binary may contain the following banned API.
> The binary may use the following weak hash API(s)
> The binary may use the following insecure Random Function(s)
> The binary may use malloc function instead of calloc.

_

Is there any way to verify if these are actual issues? Im using python3 by the way and putting through an IPA file.

**Comment by sundaramRNT** [comment]
Hi all,
During scanning of IPA file using MOBSF, we got vulnerabilities against functions  _random, MALLOC()  etc., Development team used CORDOVA library during development.  We have no idea, whether it has been fixed in the latest versions.  Can somebody suggest how to fix this issue.

**Comment by wtimme** [comment]
Hey folks, first of all: Thanks a lot for this framework and all the effort you're putting in!

We got similar messages, so I decided to analyze the zipped source code. When looking at the files that were reported to contain "banned API(s)", I wasn't able to spot anything unusual. So I had a look at [the rule for "banned API(s)"][1] and saw that it is using a regular expression to scan for these APIs:

    strcpy|memcpy|strcat|strncat|strncpy|sprintf|vsprintf|gets

When putting this into Xcode's search, I got hundreds of results. Hmm, strange. So I looked at the text that was matching and realized that the last "API", `gets`, is causing this false-positive for us. In the Objective-C files that were reported, we have documentation, e. g. 

    // Method gets called twice if permission for camera or photo library is not granted yet.

This "gets" is what was causing the "banned API(s)" warning.

To sum it up, for us this rule proved to result in some false-positives. If you're facing similar messages in your report, I suggest you scan your code base using the regular expression found in the MobSF's source code.

@ajinabraham, what do you think about changing the regular expression a bit, so that it matches `gets(`, but not `gets`?

[1]: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/aaf8c3ee7e0bb45bf89c2e64f7ebe43ed92fa94e/StaticAnalyzer/views/ios/ios_rules.py#L43

**Comment by ajinabraham** [comment]
@wtimme Yeah, we can improve that regex. Added an enhancement to track this
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1217

**Comment by sundaramRNT** [comment]
> Hey folks, first of all: Thanks a lot for this framework and all the effort you're putting in!
> 
> We got similar messages, so I decided to analyze the zipped source code. When looking at the files that were reported to contain "banned API(s)", I wasn't able to spot anything unusual. So I had a look at [the rule for "banned API(s)"](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/aaf8c3ee7e0bb45bf89c2e64f7ebe43ed92fa94e/StaticAnalyzer/views/ios/ios_rules.py#L43) and saw that it is using a regular expression to scan for these APIs:
> 
> ```
> strcpy|memcpy|strcat|strncat|strncpy|sprintf|vsprintf|gets
> ```
> 
> When putting this into Xcode's search, I got hundreds of results. Hmm, strange. So I looked at the text that was matching and realized that the last "API", `gets`, is causing this false-positive for us. In the Objective-C files that were reported, we have documentation, e. g.
> 
> ```
> // Method gets called twice if permission for camera or photo library is not granted yet.
> ```
> 
> This "gets" is what was causing the "banned API(s)" warning.
> 
> To sum it up, for us this rule proved to result in some false-positives. If you're facing similar messages in your report, I suggest you scan your code base using the regular expression found in the MobSF's source code.
> 
> @ajinabraham, what do you think about changing the regular expression a bit, so that it matches `gets(`, but not `gets`?

So, can we consider the below listed items as false positive ?
strcpy|memcpy|strcat|strncat|strncpy|sprintf|vsprintf|gets

**Comment by ajinabraham** [comment]
if you can verify it by checking the source code.

**Comment by ajinabraham** [comment]
We have a partial fix for this is 3.1.1. I don't think we can fix this completely as from binary analysis, it's difficult to get into a precise conclusion.

**Comment by delmarz** [comment]
> We have a partial fix for this is 3.1.1. I don't think we can fix this completely as from binary analysis, it's difficult to get into a precise conclusion.

I tried to re-investigate this issue it seems there something wrong while compiling the binary to development/distribution profile since it has symbols stripped.

It could be 100% false positive 

Hence it throws an unrelated error:

**Archiving to Distribution Profile** - _No insecure apis error etc_,  **But it throws (SST and ARC) error**

**Archiving to Development Profile** - _No error for (SST and ARC)_, **But it throws insecure apis error etc**

This is tested with the latest Swift 5.2.x 
Ref: you quoted last time which is related on this issue. https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/681#issuecomment-412803911

**Comment by Aparnass** [comment]
Hi @ajinabraham Could you please help me in fixing Binary Analysis and insecure API's error?

**Comment by Aparnass** [comment]
I am an iOS Developer

**Comment by MskShahrukh** [comment]
Hi there, 
I am facing a similar problem, I zipped the iOS folder to get better information and solved all high severities by making patches for pods. The score for zip ios is now in A grade! and that's great. 

But.. When I upload the .ipa build i still get the F grade result. 
And same errors.. what am I missing here ?

**Comment by nikekannan** [comment]
I am developing a iOS Framework with Objc.  It had some C implementations which uses vulnerable APIs like fopen, memcpy, strlen etc.,  So its okay that the tool highlighted them.  We then moved the implementation completely into Swift (ie., No C/C++/Objc code in the Framework).  If we scan the iPA now, we still see the same problem.  Could not locate when we search using Xcode.  We do not see the same issues reported when scanned Source code as zip.

Then i tried to scan a Vennila Swift Sample app (I have attached the iPA)
[Payload.ipa.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/15113016/Payload.ipa.zip)

I can still see the _strlen & malloc API usage errors poping up.

How to identify from which framework does these calls triggered.  Does MobSF code runs case insensitive search for keywords like fopen, memcpy, strlen, sscanf
