### ISSUE TITLE
Unable to download report from MobSF

### ISSUE THREAD

**Issue by rubaiyyaat** [MobSF/Mobile-Security-Framework-MobSF#402]
## EXPLANATION OF THE ISSUE

- Using MobSF
- When click Download Report from menu it does not generate any file

## STEPS TO REPRODUCE THE ISSUE

```
1. Conduct Static Anlysis
2. Click Download Report
3. Error
```

## CONSOLE OUTPUT

```
- Command Line shows "Can not find files for the given patterns"
```

## CONTENTS OF LOG FILES

```

- A pdf.json file gets generated which shows below error
{"pdf_error": "Cannot Generate PDF", "err_details": "No wkhtmltopdf executable found: \"\"\nIf this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf"}

**Comment by gorivishal** [comment]
PDF Report Generation

You need to install wkhtmltopdf binary separately for generating PDF reports.
Check wkhtmltopdf downloads (http://wkhtmltopdf.org/downloads.html) and Installing wkhtmltopdf wiki (https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf) for more information.
In Windows, you need to add the folder that contains wkhtmltopdf binary to environment variable PATH.

**Comment by bhavikp43** [comment]
PDF report generation error.

error - " 'bool' object has no attribute 'dumps'
Internal Server Error: /PDF/
"GET /PDF/?md5=f4b4e27d612aa4c6aeecf75da93de8f5&type=APK HTTP/1.1" 500 4848
 "

pls help

**Comment by mohite6336** [comment]
While generating static analysis report, application shows 'pdf_error' . Please help me to resolve this error.


pdf_error | "Cannot Generate PDF"
-- | --
err_details | "wkhtmltopdf exited with non-zero code 1. error:\nQt: Untested Windows version 6.2 detected!\r\nUnknown long argument --no-collate\r\n\r\nName:\r\n  wkhtmltopdf 0.9.9\r\n\r\nSynopsis:\r\n  wkhtmltopdf [OPTIONS]... <input file> [More input files] <output file>\r\n  \r\nDescription:\r\n  Converts one or more HTML pages into a PDF document, using wkhtmltopdf patched\r\n  qt.\r\n\r\nGeneral Options:\r\n  -b, --book                          Set the options one would usually set when                                      printing a book\r\n      --collate                       Collate when printing multiple copies\r\n      --copies <number>               Number of copies to print into the pdf                                      file (default 1)\r\n      --cover <url>                   Use html document as cover. It will be                                      inserted before the toc with no headers                                      and footers\r\n  -H, --default-header                Add a default header, with the name of the                                      page to the left, and the page number to                                      the right, this is short for:                                      --header-left='[webpage]'                                      --header-right='[page]/[toPage]' --top 2cm                                      --header-line\r\n      --extended-help                 Display more extensive help, detailing                                      less common command switches\r\n  -h, --help                          Display help\r\n  -O, --orientation <orientation>     Set orientation to Landscape or Portrait\r\n  -s, --page-size <size>              Set paper size to: A4, Letter, etc.\r\n      --password <password>           HTTP Authentication password\r\n  -p, --proxy <proxy>                 Use a proxy\r\n  -q, --quiet                         Be less verbose\r\n  -t, --toc                           Insert a table of content in the beginning                                      of the document\r\n      --username <username>           HTTP Authentication username\r\n  -V, --version                       Output version information an exit\r\nContact:\r\n  If you experience bugs or want to request new features please visit \r\n  <http://code.google.com/p/wkhtmltopdf/issues/list>, if you have any problems\r\n  or comments please feel free to contact me: see \r\n  <http://www.madalgo.au.dk/~jakobt/#about>\r\n\r\n"

**Comment by ajinabraham** [comment]
You probably have an unspported old version of wkhtmltopdf
Download anf configure it from https://wkhtmltopdf.org/downloads.html

**Comment by suhas-s-dev** [comment]
I have installed wkhtmltopdf and added it to path and still getting same issue. Any recommendations?

**Comment by anthnyajp** [comment]
I'm having the same issue. I tried everything mentioned and cant get it to work. Any suggestions?

: [ERROR] 23/Feb/2023 15:48:34 - Error Generating PDF Report
: Traceback (most recent call last):
: File "C:\Users\anthn\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pdfkit\configuration.py", line 35, in __init__
: with open(self.wkhtmltopdf) as f:
: FileNotFoundError: [Errno 2] No such file or directory: b''
:
: During handling of the above exception, another exception occurred:
:
: Traceback (most recent call last):
: File "C:\Users\anthn\Mobile-Security-Framework-MobSF\mobsf\StaticAnalyzer\views\common\pdf.py", line 135, in pdf
: pdf_dat = pdfkit.from_string(html, False, options=options)
: File "C:\Users\anthn\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pdfkit\api.py", line 72, in from_string
: r = PDFKit(input, 'string', options=options, toc=toc, cover=cover, css=css,
: File "C:\Users\anthn\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pdfkit\pdfkit.py", line 45, in __init__
: self.configuration = (Configuration() if configuration is None
: File "C:\Users\anthn\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pdfkit\configuration.py", line 38, in __init__
: raise IOError('No wkhtmltopdf executable found: "%s"\n'
: OSError: No wkhtmltopdf executable found: "b''"
: If this file exists please check that this process can read it or you can pass path to it manually in method call, check README. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
: [ERROR] 23/Feb/2023 15:48:34 - Internal Server Error: /pdf/
: wkhtmltopdf
