### ISSUE TITLE
Binary make use of banned API(s)

### ISSUE THREAD

**Issue by ygoncalves1999** [MobSF/Mobile-Security-Framework-MobSF#518]
Hi, I am running a scan on a iOS app and found this issue:

Binary make use of banned API(s) 
The binary may contain the following banned API(s) _stat, _strlen, _strncpy, _gets, _printf, _memcpy, _alloca.

Why can't I use these API(s)? I made a research over the internet but didn't found anything wrong with it, can you help me understand this issue? 

Thank youuu

**Comment by ajinabraham** [comment]
Strictly for bugs only. Use slack for discussions.

**Comment by migueldeicaza** [comment]
None of those APIs are banned by Apple.   This is incorrect and the issue should be reopened.

**Comment by ajinabraham** [comment]
@DominikSchlecht  any inputs here?

**Comment by DominikSchlecht** [comment]
These functions are dangerous because they might lead to memory corruption and should not be used anymore. A quick link where some of them are explained: [here](https://developer.apple.com/library/content/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1). I will look up the full list later.

**Comment by kj0317** [comment]
> 
> 
> None of those APIs are banned by Apple. This is incorrect and the issue should be reopened.

Is there a source regarding what APIs are banned and which ones aren't?

**Comment by ManigandanRaamanathan** [comment]
@ygoncalves1999 any update on this?

**Comment by karolpiateknet** [comment]
According to sent above [Apple document](https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1) some of those functions are false positive, since Apple says "Don't use `vsprintf` use `vsnprintf (see note) or vasprintf` instead, see screenshot.
![Screen Shot 2021-03-24 at 08 21 57](https://user-images.githubusercontent.com/57398986/112270467-02743100-8c7a-11eb-9c19-cbac3a67d9b5.png)

And other functions mentioned in that document as "use instead" are causing warnings. 🤔 
There is no mention about fopen in the docs, however there is mention about that `fget` should be used instead of `get`.

Above document is being placed in the archive, [the new one](https://developer.apple.com/documentation/xcode/diagnosing_memory_thread_and_crash_issues_early/overflow_and_underflow_of_buffers) I see that it doesn't contain such recommendations.

**Comment by eduardboamba** [comment]
5 years later and such findings still come up with severity "high", without providing any inclusion path. Would be great to have this reassessed.
