### ISSUE TITLE
 Configuring dynamic analyzer failure 

### ISSUE THREAD

**Issue by jiangsi520** [MobSF/Mobile-Security-Framework-MobSF#649]
During the dynamic debugging phase, when I clicked on the creation environment, I was unable to connect to VM/Dervice 192.168.56.101:5555

My VM's IP is the 192.168.56.1 port is 1337
![image](https://user-images.githubusercontent.com/30169495/41457485-63477f6a-70b6-11e8-8cfc-694c96d728ef.png)

![image](https://user-images.githubusercontent.com/30169495/41457792-60f0db5c-70b7-11e8-81f9-d3b3668f0451.png)

![image](https://user-images.githubusercontent.com/30169495/41457838-858cfd2e-70b7-11e8-938e-95b432271121.png)

**Comment by ajinabraham** [comment]
Are you sure your VM IP is `192.168.56.101` Is that the one displayed on the VM?
Also kill all existing adb process while you run MobSF (a running Android studio will respawn adb)
Kill any other android emulators, VMs, devices connected to system etc.

**Comment by jiangsi520** [comment]
The problem is that VM_IP can't find it. I set it in settings.py, but look at your installation instructions, and when the VM is opened, it doesn't get the VM_IP in your screenshot. My environment is win10+oracle VM Virtualbox +MobSF_VM_0.2.ova.

Can you tell me where VM_IP refers to IP? Also, how should VM_IP be set up?

 The picture below is the picture in your tutorial ：
![image](https://user-images.githubusercontent.com/30169495/41574599-ef49b884-73b3-11e8-94b0-050025eb6df6.png)

This is the configuration after my VM startup. From the diagram, I should have failed to get VM_IP.

![b15 fj u bk 90fb ly6i c](https://user-images.githubusercontent.com/30169495/41575550-89ad714e-73b5-11e8-8879-9e5ed669fbb2.png)
![y3r q _mnxn82 clj2nba44](https://user-images.githubusercontent.com/30169495/41575559-93f6810e-73b5-11e8-8d18-abe33a899c07.png)

**Comment by ajayraina143** [comment]
Don't Play Around. An Error just popped in!

Inappropriate argument type.

'NoneType' object is not subscriptable


[INFO] 04/Mar/2019 13:38:53 - Mobile Security Framework v1.0.5 Beta
REST API Key: f6eca7846d5bb2ce795023b9712de36ce8254a2ad0bc052ab5eb320b0be6b56c
[INFO] 04/Mar/2019 13:38:53 - OS: Linux
[INFO] 04/Mar/2019 13:38:53 - Platform: Linux-4.19.0-kali1-amd64-x86_64-with-Ubuntu-18.04-bionic
[INFO] 04/Mar/2019 13:38:54 - Dist: ('Ubuntu', '18.04', 'bionic')
[INFO] 04/Mar/2019 13:38:54 - Finding JDK Location in Linux/MAC....
[INFO] 04/Mar/2019 13:38:54 - JDK 1.7 or above is available
[WARNING] 04/Mar/2019 13:38:54 - Could not find VirtualBox path.
[INFO] 04/Mar/2019 13:38:54 - MobSF Basic Environment Check
[INFO] 04/Mar/2019 13:38:54 - Checking for Update.
[INFO] 04/Mar/2019 13:38:54 - No updates available.
System check identified no issues (0 silenced).
March 04, 2019 - 13:38:54
Django version 2.1.7, using settings 'MobSF.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[INFO] 04/Mar/2019 13:38:59 - "GET / HTTP/1.1" 200 7723
[INFO] 04/Mar/2019 13:39:16 - MIME Type: application/vnd.android.package-archive FILE: dishmagicsales (1).apk
[INFO] 04/Mar/2019 13:39:16 - Performing Static Analysis of Android APK
[INFO] 04/Mar/2019 13:39:16 - "POST /upload/ HTTP/1.1" 200 229
[INFO] 04/Mar/2019 13:39:16 - Starting Analysis on : DishMagicSales (1).apk
[INFO] 04/Mar/2019 13:39:16 - Generating Hashes
[INFO] 04/Mar/2019 13:39:16 - Unzipping
[ERROR] 04/Mar/2019 13:39:16 - 
Unzipping Error (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/shared_func.py, LINE 78 "with zipfile.ZipFile(app_path, "r") as zipptr:"): File is not a zip file
[INFO] 04/Mar/2019 13:39:16 - Using the Default OS Unzip Utility.
[ERROR] 04/Mar/2019 13:39:16 - 
Unzipping Error (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/shared_func.py, LINE 95 "['unzip', '-o', '-I utf-8', '-q', app_path, '-d', ext_path])"): [Errno 2] No such file or directory: 'unzip': 'unzip'
[INFO] 04/Mar/2019 13:39:16 - Getting Hardcoded Certificates/Keystores
[ERROR] 04/Mar/2019 13:39:16 - 
Getting Hardcoded Certificates/Keystores (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 26 "for file_name in files:"): 'NoneType' object is not iterable
[INFO] 04/Mar/2019 13:39:16 - APK Extracted
[INFO] 04/Mar/2019 13:39:16 - Converting AXML to XML
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:307)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
	... 3 more
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1529)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1430)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1437)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1268)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1231)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:190)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
[ERROR] 04/Mar/2019 13:39:17 - 
Getting Manifest file (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 888 "subprocess.check_output(args)"): Command '['/usr/bin/java', '-jar', '/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apktool_2.3.4.jar', '--match-original', '-f', '-s', 'd', '/root/.MobSF/uploads/a76f2f10a70619a6422d185b4f04a91f/a76f2f10a70619a6422d185b4f04a91f.apk', '-o', '/root/.MobSF/uploads/a76f2f10a70619a6422d185b4f04a91f/apktool_out']' returned non-zero exit status 1.
[ERROR] 04/Mar/2019 13:39:17 - 
Reading Manifest file (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 843 "if isFileExists(manifest):"): stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] 04/Mar/2019 13:39:17 - Parsing AndroidManifest.xml
[ERROR] 04/Mar/2019 13:39:17 - 
apktool failed to extract AndroidManifest.xml or parsing failed (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 34 "manifest = minidom.parseString(dat)"): a bytes-like object is required, not 'NoneType'
[WARNING] 04/Mar/2019 13:39:17 - Using Fake XML to continue the Analysis
[INFO] 04/Mar/2019 13:39:17 - Extracting Manifest Data
[INFO] 04/Mar/2019 13:39:17 - Manifest Analysis Started
[INFO] 04/Mar/2019 13:39:17 - Static Android Binary Analysis Started
[INFO] 04/Mar/2019 13:39:17 - Static Android Resource Analysis Started
[INFO] 04/Mar/2019 13:39:17 - Reading Code Signing Certificate
[ERROR] 04/Mar/2019 13:39:17 - 
Reading Code Signing Certificate (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 52 "cert) if os.path.isfile(os.path.join(cert, f))]"): [Errno 2] No such file or directory: '/root/.MobSF/uploads/a76f2f10a70619a6422d185b4f04a91f/META-INF/'
[INFO] 04/Mar/2019 13:39:17 - Running APKiD 1.2.1 on: a76f2f10a70619a6422d185b4f04a91f.apk
2019-03-04 13:39:17 ERROR    error extracting /root/.MobSF/uploads/a76f2f10a70619a6422d185b4f04a91f/apkid/a76f2f10a70619a6422d185b4f04a91f.apk: File is not a zip file
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apkid/apkid.py", line 145, in scan_apk
    zf = zipfile.ZipFile(apk_path, 'r')
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

[INFO] 04/Mar/2019 13:39:17 - DEX -> JAR
[INFO] 04/Mar/2019 13:39:17 - Using JAR converter - dex2jar
[INFO] 04/Mar/2019 13:39:17 - DEX -> SMALI
[INFO] 04/Mar/2019 13:39:17 - JAR -> JAVA
[INFO] 04/Mar/2019 13:39:17 - Static Android Code Analysis Started
[INFO] 04/Mar/2019 13:39:17 - Code Analysis Started on - java_source
[INFO] 04/Mar/2019 13:39:17 - Performing Malware Check on extracted Domains
[INFO] 04/Mar/2019 13:39:17 - Finished Code Analysis, Email and URL Extraction
[INFO] 04/Mar/2019 13:39:17 - Generating Java and Smali Downloads
[INFO] 04/Mar/2019 13:39:17 - Generating Downloads
[INFO] 04/Mar/2019 13:39:17 - Zipping
[INFO] 04/Mar/2019 13:39:17 - Zipping
[INFO] 04/Mar/2019 13:39:17 - Extracting Strings from APK
[ERROR] 04/Mar/2019 13:39:17 - 
Extracting Strings from APK (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/strings.py, LINE 24 "and_a = apk.APK(apk_file)"): File is not a zip file
[INFO] 04/Mar/2019 13:39:17 - Connecting to Database
[INFO] 04/Mar/2019 13:39:17 - Saving to Database
[ERROR] 04/Mar/2019 13:39:17 - 
Saving to DB (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 221 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[ERROR] 04/Mar/2019 13:39:17 - 
Rendering to Template (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 108 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[ERROR] 04/Mar/2019 13:39:17 - 'NoneType' object is not subscriptable
[ERROR] 04/Mar/2019 13:39:17 - Internal Server Error: /StaticAnalyzer/
2019-03-04 13:39:17 ERROR    Internal Server Error: /StaticAnalyzer/
[ERROR] 04/Mar/2019 13:39:17 - "GET /StaticAnalyzer/?name=DishMagicSales%20(1).apk&type=apk&checksum=a76f2f10a70619a6422d185b4f04a91f HTTP/1.1" 500 4848
2019-03-04 13:39:17 ERROR    "GET /StaticAnalyzer/?name=DishMagicSales%20(1).apk&type=apk&checksum=a76f2f10a70619a6422d185b4f04a91f HTTP/1.1" 500 4848

**Comment by ajayraina143** [comment]
Don't Play Around. An Error just popped in!

Inappropriate argument type.

'NoneType' object is not subscriptable
