### ISSUE TITLE
module 'yara' has no attribute 'load'

### ISSUE THREAD

**Issue by littleheary** [MobSF/Mobile-Security-Framework-MobSF#714]
Don't Play Around. An Error just popped in!

Attribute not found.

module 'yara' has no attribute 'load'

what can i do ?

**Comment by ajinabraham** [comment]
Read Documentation before enabling APKID

**Comment by risoares** [comment]
Hi buddies, I"m experiencing the same problem with module 'yara' to perform the APKiD feature, even after running the procedures for activating APKiD. Do you have any idea for this issue; please could you help me

**Comment by ajinabraham** [comment]
Yara is not installed properly

**Comment by risoares** [comment]
Hi Ajin, I still experiencing the same issue trying to using APKiD from MobSF:  module 'yara' has no attibute 'load': I already installed Yara 3.8.1 properly, according to the procedures https://yara.readthedocs.io/en/v3.8.1/gettingstarted.html, installed the yara-python from rednaga fork from MobSF documentation guide https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation. I don't know what to do anymore.
if you have any other idea, please help me. Thanks in advance !

**Comment by ajinabraham** [comment]
@risoares You need to install rednaga fork of yara.

```
git clone --recursive https://github.com/rednaga/yara-python-1 yara-python
cd yara-python
python3 setup.py build --enable-dex install
```

Make sure you do it outside virtualenv. (Needs to be installed as a system package)

**Comment by risoares** [comment]
Ajin, I did this settings sent by you but still receiving the same error; 

INFO] APKiD Analysis on Dex file
[ERROR] module 'yara' has no attribute 'load'
Internal Server Error: /StaticAnalyzer/

Just to clarify:

- I'm running MobSF on Kali Linux; using downloaded folder from github, not using docker image;
- on kali Linux packages is listed only yara 3.8.1-2;
- APKiD and Yara is installed properly although APKiD is not listed on kali linux packages:

pip install apkid
Requirement already satisfied: apkid in ./APKiD (1.2.1)
Requirement already satisfied: argparse in /usr/lib/python2.7 (from apkid) (1.2.1)
Requirement already satisfied: yara-python==3.7.0.999 in /usr/local/lib/python2.7/dist-packages/yara_python-3.7.0.999-py2.7-linux-x86_64.egg (from apkid) (3.7.0.999)

pip install yara-python
Requirement already satisfied: yara-python in /usr/local/lib/python2.7/dist-packages/yara_python-3.7.0.999-py2.7-linux-x86_64.egg (3.7.0.999)

Is it possible run the APKiD outside of docker image installation ...
I'm running the MobSF using ./run.sh command because python manage.py prompt me the errors below ( don't know if there are related issues with this):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 13, in <module>
    from MobSF import utils
  File "/root/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 25, in <module>
    from . import settings
ImportError: cannot import name settings

Thanks in advance for any consideration.

**Comment by ajinabraham** [comment]
MobSF is Python3 and we use python 3.6+ version of APKiD

**Comment by ajinabraham** [comment]
This is not a bug, for discussion please use slack channel

**Comment by risoares** [comment]
Hi Ajin, How could I find you in slack channel for a discussion regarding APKiD vs MobSF ? Thanks
