### ISSUE TITLE
Can't start Dynamic Analysis

### ISSUE THREAD

**Issue by johmc** [MobSF/Mobile-Security-Framework-MobSF#732]
Cannot Connect to the VM/Device. ('ERROR Connecting to VM/Device. ', 'unable to connect to 192.168.56.101:5555: No route to host')

Please help me with this one.

Currently using it using docker.

[INFO] Setting up Dynamic Analysis Environment

[INFO] Connecting to VM/Device
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
Capture Module Loaded
Proxy server listening at http://*:1337

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device
[18/Sep/2018 04:02:39] "POST /GetEnv/ HTTP/1.1" 200 168

**Comment by ajinabraham** [comment]
Read docs clearly before opening bugs unnecessarily 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#installation

**Comment by johmc** [comment]
k

**Comment by ZapDos7** [comment]
I had the exact same issue. In the documentation, I have found the clause that dynamic analysis won't work if set up on docker or VM. So, I installed it in my OS. But, I get a connection to host error and dynamic analysis won't start.

Since I _have_ read the documentation, is there an actual solution/tip to counter this issue? Thanks :)

**Comment by ajinabraham** [comment]
Make sure the host and the VM are in same network range. This connections errors happen mainly when 
1. Something in host is blocking the connection
2. They are running in different IP range.
Also see: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/6.-What-to-do-when-MobSF-VM-and-VirtualBox-Host-Only-Adapter-are-not-in-the-same-network-range
