### ISSUE TITLE
None type Error Apk

### ISSUE THREAD

**Issue by Polibus** [MobSF/Mobile-Security-Framework-MobSF#735]
## EXPLANATION OF THE ISSUE
Hi i have the problem with an android app the strange is that the other day MOBSF worked and analized the app well
I attached the log file and the link of the APK
info: I'm using the docker container on ubuntu x64 18.04 
[APK](https://play.google.com/store/apps/details?id=be.delen.digital&hl=en)
[log.log](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/2408145/log.log)

**Comment by superpoussin22** [comment]
@Polibus  can you try branch: fix_encoding ? it should solve your issue

**Comment by ccsplit** [comment]
@superpoussin22, there still appears to be an issue with that branch, in which `filename` is still not set. It appears [this change](https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/27aaae197ae8ec8ebddf3f78ef2d5c53fa55bff6#diff-70f9602599a659f863110d8147c81cbaL78) causes the issue since `filename = fileinfo.filename` was removed. Added this line back removes the issue for me at least.

**Comment by ajinabraham** [comment]
Fixed in latest master
