### ISSUE TITLE
./run.sh: line 5: venv/bin/activate: No such file or directory

### ISSUE THREAD

**Issue by Lex-wa** [MobSF/Mobile-Security-Framework-MobSF#915]
I finish the install，and begin it with "./run.sh". but have an error like this:
./run.sh: line 5: venv/bin/activate: No such file or directory

**Comment by Lex-wa** [comment]
I have resolve it after reading the document again.thanks!

**Comment by EstherZurita** [comment]
I have the same error please support me to correct it

**Comment by ajinabraham** [comment]
Make sure setup.sh executed correctly and `python3 -m venv ./venv` runs successfully.

**Comment by EstherZurita** [comment]
this is the result for setup.sh 

root@kali:~/Mobile-Security-Framework-MobSF# ./setup.sh
[INSTALL] Found Python3
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
[INSTALL] Found pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Downloading https://files.pythonhosted.org/packages/8d/07/f7d7ced2f97ca3098c16565efbe6b15fafcba53e8d9bdb431e09140514b0/pip-19.2.2-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 56kB/s 
Installing collected packages: pip
  Found existing installation: pip 18.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-19.2.2
[INSTALL] Using venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/root/Mobile-Security-Framework-MobSF/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

./setup.sh: line 43: venv/bin/activate: No such file or directory
[INSTALL] Installing APKiD requirements - yara-python
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.32.3)
/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/wheel.py:109: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting git+https://github.com/VirusTotal/yara-python.git
  Cloning https://github.com/VirusTotal/yara-python.git to /tmp/pip-req-build-hhrk3ann
  Running command git clone -q https://github.com/VirusTotal/yara-python.git /tmp/pip-req-build-hhrk3ann
  Running command git submodule update --init --recursive -q
Building wheels for collected packages: yara-python
  Building wheel for yara-python (setup.py) ... done
  Created wheel for yara-python: filename=yara_python-3.10.0-cp37-cp37m-linux_i686.whl size=558541 sha256=d3255e4e024b6756a3846e59e0a9fa1b80678ab0a67b1874e056e2db244e7550
  Stored in directory: /tmp/yara-python
Successfully built yara-python
Looking in links: /tmp/yara-python
Collecting yara-python
Installing collected packages: yara-python
Successfully installed yara-python-3.10.0
[INSTALL] Installing Requirements
Requirement already satisfied: cryptography==2.6.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.6.1)
Collecting Django==2.2.4 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d6/57/66997ca6ef17d2d0f0ebcd860bc6778095ffee04077ca8985928175da358/Django-2.2.4-py3-none-any.whl
Collecting pdfkit==0.6.1 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/57/da/48fdd627794cde49f4ee7854d219f3a65714069b722b8d0e3599cd066185/pdfkit-0.6.1-py3-none-any.whl
Collecting androguard==3.3.5 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/43/ca/09deda747e28903e742768918480083682799abbe31c5e1ba5dbe7eeaf4b/androguard-3.3.5-py3-none-any.whl
Collecting lxml==4.3.3 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/93/97/41f8f6ce435dd668f966805336c54d6c8fc6a6b982bbd5a2c960d1992592/lxml-4.3.3-cp37-cp37m-manylinux1_i686.whl
Collecting rsa==4.0 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting biplist==1.0.3 (from -r requirements.txt (line 7))
Collecting requests==2.22.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting bs4==0.0.1 (from -r requirements.txt (line 9))
Collecting colorlog==4.0.2 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl
Collecting macholib==1.11 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/41/f1/6d23e1c79d68e41eb592338d90a33af813f98f2b04458aaf0b86908da2d8/macholib-1.11-py2.py3-none-any.whl
Collecting google-play-scraper==0.0.1.1 (from -r requirements.txt (line 12))
Collecting whitenoise==4.1.3 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/96/75/92afb2d8912ac19646f67a2c69bb8683e5aab78db3b0791bfd3e7ed022bb/whitenoise-4.1.3-py2.py3-none-any.whl
Collecting click==6.7 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting pyparsing==2.2.2 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/2b/4a/f06b45ab9690d4c37641ec776f7ad691974f4cf6943a73267475b05cbfca/pyparsing-2.2.2-py2.py3-none-any.whl
Collecting capfuzz==0.0.1 (from -r requirements.txt (line 16))
Collecting waitress==1.3.0 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/41/e0/366785e4b9b4d212df4c3b084153bf7f5e5ab355928f5465144e5fc98494/waitress-1.3.0-py2.py3-none-any.whl
Collecting gunicorn==19.9.0 (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl
Collecting apkid==2.0.3 (from -r requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/ac/85/1bca460c38af3183db7d20252c49bb58c3cb8c5de179c17246317599e14d/apkid-2.0.3-py2.py3-none-any.whl
Collecting sqlparse (from Django==2.2.4->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from Django==2.2.4->-r requirements.txt (line 2)) (2019.1)
Requirement already satisfied: asn1crypto>=0.24.0 in /usr/lib/python3/dist-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (0.24.0)
Requirement already satisfied: pygments in /usr/lib/python3/dist-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (2.3.1)
Collecting networkx>=1.11 (from androguard==3.3.5->-r requirements.txt (line 4))
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (0.3.7)
Collecting ipython>=5.0.0 (from androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/f6/c4/a79582814bdfe92bfca4d286a729304ffdf13f5135132cfcaea13cf1b2b3/ipython-7.7.0-py3-none-any.whl
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (0.16.0)
Collecting pydot>=1.4.1 (from androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/33/d1/b1479a770f66d962f545c2101630ce1d5592d90cb4f083d38862e93d16d2/pydot-1.4.1-py2.py3-none-any.whl
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (3.0.2)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa==4.0->-r requirements.txt (line 6)) (0.4.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.22.0->-r requirements.txt (line 8)) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.22.0->-r requirements.txt (line 8)) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.22.0->-r requirements.txt (line 8)) (2018.8.24)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.22.0->-r requirements.txt (line 8)) (3.0.4)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4==0.0.1->-r requirements.txt (line 9)) (4.7.1)
Collecting altgraph>=0.15 (from macholib==1.11->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/0a/cc/646187eac4b797069e2e6b736f14cdef85dbe405c9bfc7803ef36e4f62ef/altgraph-0.16.1-py2.py3-none-any.whl
Collecting mitmproxy==3.0.2 (from capfuzz==0.0.1->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/90/7b/09d4c6140f56cd6834c5ae320908795d0df2641a2cba694d7343e3a930c7/mitmproxy-3.0.2-py3-none-any.whl
Requirement already satisfied: yara-python==3.10.0 in /usr/local/lib/python3.7/dist-packages (from apkid==2.0.3->-r requirements.txt (line 19)) (3.10.0)
Collecting argparse (from apkid==2.0.3->-r requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Requirement already satisfied: decorator>=4.3.0 in /usr/lib/python3/dist-packages (from networkx>=1.11->androguard==3.3.5->-r requirements.txt (line 4)) (4.3.0)
Requirement already satisfied: traitlets>=4.2 in /usr/lib/python3/dist-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (4.3.2)
Collecting jedi>=0.10 (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/55/54/da994f359e4e7da4776a200e76dbc85ba5fc319eefc22e33d55296d95a1d/jedi-0.15.1-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl
Collecting pickleshare (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3/dist-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (40.8.0)
Collecting backcall (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4))
Collecting prompt-toolkit<2.1.0,>=2.0.0 (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/f7/a7/9b1dd14ef45345f186ef69d175bdd2491c40ab1dfa4b2b3e4352df719ed7/prompt_toolkit-2.0.9-py3-none-any.whl
Collecting sortedcontainers<1.6,>=1.5.4 (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/1f/ba/215c652f38197729189a3c15971b4914c4650b2dbc556ea516c8b5509e8b/sortedcontainers-1.5.10-py2.py3-none-any.whl
Collecting tornado<4.6,>=4.3 (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16))
Requirement already satisfied: h2<4,>=3.0.1 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (3.0.1)
Requirement already satisfied: pyperclip<1.7,>=1.5.22 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (1.6.4)
Requirement already satisfied: kaitaistruct<0.9,>=0.7 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (0.8)
Requirement already satisfied: blinker<1.5,>=1.4 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (1.4)
Requirement already satisfied: hyperframe<6,>=5.1.0 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (5.1.0)
Requirement already satisfied: passlib<1.8,>=1.6.5 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (1.7.1)
Collecting brotlipy<0.8,>=0.7.0 (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16))
Requirement already satisfied: ruamel.yaml<0.16,>=0.13.2 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (0.15.34)
Collecting pyOpenSSL<17.6,>=17.5 (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/79/db/7c0cfe4aa8341a5fab4638952520d8db6ab85ff84505e12c00ea311c3516/pyOpenSSL-17.5.0-py2.py3-none-any.whl
Collecting ldap3<2.5,>=2.4 (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/5a/fc/746bebdb9362dff76291aba17393381d30fcb99415b7143f4ddca865995d/ldap3-2.4.1-py2.py3-none-any.whl
Requirement already satisfied: wsproto<0.12.0,>=0.11.0 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (0.11.0)
Requirement already satisfied: urwid<2.1,>=2.0.1 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (2.0.1)
Collecting h11<0.8,>=0.7.0 (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/97/57/c0734cec5a9344d1feab295046011edbc6ba8e877ce1b822373257acdb61/h11-0.7.0-py2.py3-none-any.whl
Collecting parso>=0.5.0 (from jedi>=0.10->ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a3/bd/bf4e5bd01d79906e5b945a7af033154da49fd2b0d5b5c705a21330323305/parso-0.5.1-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (1.12.0)
Collecting wcwidth (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting cffi>=1.0.0 (from brotlipy<0.8,>=0.7.0->mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/a8/ae/399e51b2c82cc7969c2568ebe4cc5559d522bf5e9ab3d8fe8a2fb6b5b5d3/cffi-1.12.3-cp37-cp37m-manylinux1_i686.whl
Collecting pycparser (from cffi>=1.0.0->brotlipy<0.8,>=0.7.0->mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16))
ERROR: mitmproxy 3.0.2 has requirement cryptography<2.2,>=2.1.4, but you'll have cryptography 2.6.1 which is incompatible.
Installing collected packages: sqlparse, Django, pdfkit, networkx, parso, jedi, ptyprocess, pexpect, pickleshare, backcall, wcwidth, prompt-toolkit, ipython, lxml, pyparsing, pydot, click, androguard, rsa, biplist, requests, bs4, colorlog, altgraph, macholib, google-play-scraper, whitenoise, sortedcontainers, tornado, pycparser, cffi, brotlipy, pyOpenSSL, ldap3, h11, mitmproxy, capfuzz, waitress, gunicorn, argparse, apkid
  Found existing installation: lxml 4.3.2
    Uninstalling lxml-4.3.2:
      Successfully uninstalled lxml-4.3.2
  Found existing installation: pyparsing 2.2.0
    Uninstalling pyparsing-2.2.0:
      Successfully uninstalled pyparsing-2.2.0
  Found existing installation: Click 7.0
    Uninstalling Click-7.0:
      Successfully uninstalled Click-7.0
  Found existing installation: requests 2.21.0
    Uninstalling requests-2.21.0:
      Successfully uninstalled requests-2.21.0
  Found existing installation: sortedcontainers 2.0.4
    Uninstalling sortedcontainers-2.0.4:
      Successfully uninstalled sortedcontainers-2.0.4
  Found existing installation: tornado 5.1.1
    Uninstalling tornado-5.1.1:
      Successfully uninstalled tornado-5.1.1
  Found existing installation: pyOpenSSL 19.0.0
    Uninstalling pyOpenSSL-19.0.0:
      Successfully uninstalled pyOpenSSL-19.0.0
  Found existing installation: ldap3 2.5.1
    Uninstalling ldap3-2.5.1:
      Successfully uninstalled ldap3-2.5.1
  Found existing installation: h11 0.8.1
    Uninstalling h11-0.8.1:
      Successfully uninstalled h11-0.8.1
  Found existing installation: mitmproxy 4.0.4
    Uninstalling mitmproxy-4.0.4:
      Successfully uninstalled mitmproxy-4.0.4
Successfully installed Django-2.2.4 altgraph-0.16.1 androguard-3.3.5 apkid-2.0.3 argparse-1.4.0 backcall-0.1.0 biplist-1.0.3 brotlipy-0.7.0 bs4-0.0.1 capfuzz-0.0.1 cffi-1.12.3 click-6.7 colorlog-4.0.2 google-play-scraper-0.0.1.1 gunicorn-19.9.0 h11-0.7.0 ipython-7.7.0 jedi-0.15.1 ldap3-2.4.1 lxml-4.3.3 macholib-1.11 mitmproxy-3.0.2 networkx-2.3 parso-0.5.1 pdfkit-0.6.1 pexpect-4.7.0 pickleshare-0.7.5 prompt-toolkit-2.0.9 ptyprocess-0.6.0 pyOpenSSL-17.5.0 pycparser-2.19 pydot-1.4.1 pyparsing-2.2.2 requests-2.22.0 rsa-4.0 sortedcontainers-1.5.10 sqlparse-0.3.0 tornado-4.5.3 waitress-1.3.0 wcwidth-0.1.7 whitenoise-4.1.3
[INSTALL] Clean Up

=======================MobSF Clean Script for Unix=======================
Running this script will delete the Scan database, all files uploaded and generated.

Deleting all Uploads
Deleting all Downloads
Deleting Static Analyzer Migrations
Deleting Dynamic Analyzer Migrations
Deleting MobSF Migrations
Deleting python byte code files
Deleting temp and log files
Deleting DB
Deleting Secret File
Done
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 12, in <module>
    from MobSF.utils import (find_java_binary, find_vboxmange_binary, first_run,
  File "/root/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 24, in <module>
    from . import settings
ImportError: cannot import name settings
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 12, in <module>
    from MobSF.utils import (find_java_binary, find_vboxmange_binary, first_run,
  File "/root/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 24, in <module>
    from . import settings
ImportError: cannot import name settings
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 12, in <module>
    from MobSF.utils import (find_java_binary, find_vboxmange_binary, first_run,
  File "/root/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 24, in <module>
    from . import settings
ImportError: cannot import name settings
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete

**Comment by ajinabraham** [comment]
If you could read the logs once.

The virtual environment was not created successfully because ensurepip is not
available. On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

apt-get install python3-venv

**Comment by EstherZurita** [comment]
it works thank you very much, however it doesn't let me scan ipa files i get the following error


Don't Play Around. An Error just popped in!

Inappropriate argument type.

'NoneType' object does not support item assignment


please help

**Comment by ajinabraham** [comment]
Use slack channel for support. GitHub issues are only for bug reports

**Comment by EstherZurita** [comment]
I understand thanks for your help

**Comment by Oz-Shalev** [comment]
Try to set your workdir as the Mobile-Security-Framework-MobSF, I automatically run this utility from Docker and I use - WORKDIR /opt/Mobile-Security-Framework-MobSF and it runs smoothly, whenever I change that I experience the same error you are experiencing.
