### ISSUE TITLE
Linux can not class dump the ipa

### ISSUE THREAD

**Issue by ChanJaWe** [MobSF/Mobile-Security-Framework-MobSF#996]
I have failed to class dump the binary file  in the linux os and  error message show:
class-dump-z/class-dump-swift failed on this binary
but it can run other jtool.ELF64 commands such as 
jtool.ELF64  -arch  arm  -L  -v  bin_path

**Comment by ajinabraham** [comment]
clussdumpz will work only on mac

**Comment by ajinabraham** [comment]
We normally run classdump only on Darwin. There is a bug in master.

**Comment by ChanJaWe** [comment]
if the jtool.ELF64 can dump the binary file? i can find the code in binary_analysis.py -- def class_dump:
        elif platform.system() == 'Linux':
            logger.info('Running jtool against the binary for dumping classes')
            if len(settings.JTOOL_BINARY) > 0 and isFileExists(settings.JTOOL_BINARY):
                jtool_bin = settings.JTOOL_BINARY
            else:
                jtool_bin = os.path.join(tools_dir, 'jtool.ELF64')
            subprocess.call(['chmod', '777', jtool_bin])
            args = [jtool_bin, '-arch', 'arm', '-d', 'objc', '-v', bin_path]

**Comment by ajinabraham** [comment]
I just rechecked the source it looks fine. So class dump doesn't run on non Darwin Os. We run jtool instead.
Do you have the logs for your issue.

**Comment by ChanJaWe** [comment]
I try to run the command 'jtool.ELF64 -arch arm -d objc -v bin_path' in terminal, the logs show:
Segmentation fault (core dumped)
and have no other logs

**Comment by ajinabraham** [comment]
Then probably something from the input is causing the crash. You might need to talk with the jtool developer.

**Comment by ChanJaWe** [comment]
OK, thanks for your help.

**Comment by KirubakaranK17** [comment]
@ajinabraham  Please help on this below issue, I have pulled the latest code from MOBSF master while running on .ipa file below error getting displayed. So that  Malware Analysis is not getting displayed

Select an architecture setting the ARCH= environment variable

[INFO] 11/Mar/2020 08:56:04 - Running jtool against the binary for dumping classes
[ERROR] 11/Mar/2020 08:56:09 - class-dump/class-dump-swift failed on this binary
[INFO] 11/Mar/2020 08:56:09 - Running strings against the Binary

**Comment by ajinabraham** [comment]
@KirubakaranK17 Are you sure it's the latest master. We have added a fix for jtool two days back. If you are on the latest, Can you share the IPA.
